{
 "title": "VM",
 "description": "Vitual Machine Metrics from Libvirt Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "clamp_min(irate(libvirt_domain_cpu_time_sys{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s]), 0) / 1000",
     "legendFormat": "sys"
    },
    {
     "expr": "clamp_min(irate(libvirt_domain_cpu_time_user{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s]), 0) / 1000",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "CPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "clamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"cpu_cycles\"}[3s]), 0)\n/on(domain)\nclamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[3s]), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[3s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VCPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_vcpu_time_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context Switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "clamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"context_switch\"}[3s]) , 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MKPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "1000 * clamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\",instance=\"worknode:9177\", job=\"libvirt_exporter\",event=\"cache_misses\"}[3s]), 0)\n/on(domain)\nclamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[3s]), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100 * (libvirt_domain_memory_stats_available_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}\r\n - libvirt_domain_memory_stats_unused_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"})\r\n / libvirt_domain_memory_stats_actual_balloon_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance) / 1024",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance) / 1024",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_packets_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_packets_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance)",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "Block IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 37 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_requests_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance, job)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_requests_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[3s])) by(domain, instance, job)",
     "legendFormat": "read"
    }
   ]
  }
 ]
}